// ─────────────────────────────────────────────────────────────
// SQL Race Examples: End-to-End Example Tests
// ─────────────────────────────────────────────────────────────
//
// Verified-input / verified-output tests. A deterministic session is generated by
// VerifiedFixture (every sample produced by a closed-form formula), then the operations
// the examples demonstrate are run against it and asserted to produce the values that
// formula implies. Inputs are known, so the correct outputs are known.
//
// Requires the SQL Race runtime + licence (local/licenced runner only — not GitHub CI).
// Run: dotnet test --filter "FullyQualifiedName~EndToEnd"
// ─────────────────────────────────────────────────────────────

using Xunit;
using SqlRace.Examples.Core;
using SqlRace.Examples.Fixtures;
using MESL.SqlRace.Domain;
using MESL.SqlRace.Domain.Query;
using MESL.SqlRace.Domain.Infrastructure.DataPipeline;
using MESL.SqlRace.Enumerators;

namespace SqlRace.Examples.Tests;

/// <summary>
/// Generates the verified session once into a throwaway SQLite file shared by the test class.
/// </summary>
public sealed class VerifiedSessionFixture : IDisposable
{
    public string DbPath { get; }
    public string ConnectionString { get; }

    public VerifiedSessionFixture()
    {
        DbPath = Path.Combine(Path.GetTempPath(), $"verified-e2e-{Guid.NewGuid():N}.ssn2");
        ConnectionString = ConnectionStringProvider.ForSQLiteFile(DbPath);
        VerifiedFixture.Generate(ConnectionString);
    }

    public void Dispose()
    {
        if (File.Exists(DbPath))
        {
            try { File.Delete(DbPath); } catch { /* best effort */ }
        }
    }
}

public class EndToEndExampleTests : IClassFixture<VerifiedSessionFixture>
{
    private readonly VerifiedSessionFixture _fixture;

    public EndToEndExampleTests(VerifiedSessionFixture fixture) => _fixture = fixture;

    private IClientSession LoadSession()
    {
        var sessionManager = SessionManager.CreateSessionManager();
        return sessionManager.Load(VerifiedFixture.Key, _fixture.ConnectionString);
    }

    [Fact]
    public void LoadSummary_MatchesGeneratedShape()
    {
        using var client = LoadSession();
        var session = client.Session;

        Assert.Equal(VerifiedFixture.SessionName, session.Identifier);
        Assert.Equal(VerifiedFixture.ParameterCount, session.Parameters.Count);
        Assert.Equal(VerifiedFixture.StartTimeNs, session.StartTime);
    }

    [Fact]
    public void QueryByMetadata_FindsTheSession()
    {
        using var queryManager = QueryManager.CreateQueryManager(_fixture.ConnectionString);
        var summaries = queryManager.ExecuteQuery().ToList();

        Assert.Contains(summaries, s => s.Identifier == VerifiedFixture.SessionName);
    }

    [Fact]
    public void ReadTemperature_ReturnsRampMatchingTheFormula()
    {
        using var client = LoadSession();
        var session = client.Session;

        using var pda = session.CreateParameterDataAccess(VerifiedFixture.TemperatureId);
        var samples = pda.GetSamplesBetween(session.StartTime, session.EndTime);

        Assert.Equal(VerifiedFixture.TemperatureSampleCount, samples.SampleCount);
        Assert.Equal(VerifiedFixture.StartTimeNs, samples.Timestamp[0]);
        Assert.Equal(VerifiedFixture.Temperature(0), samples.Data[0], precision: 6);
        // Note: samples.Data is a capacity buffer — only [0, SampleCount) is valid data.
        Assert.Equal(VerifiedFixture.Temperature(samples.SampleCount - 1), samples.Data[samples.SampleCount - 1], precision: 6);
    }

    [Fact]
    public void ReadFirstSecond_ReturnsExactlyTheExpectedWindow()
    {
        using var client = LoadSession();
        var session = client.Session;

        var interval = new Frequency(VerifiedFixture.TemperatureHz, FrequencyUnit.Hz).ToInterval();
        // 100 samples: indices 0..99 inclusive.
        var end = session.StartTime + 99 * interval;

        using var pda = session.CreateParameterDataAccess(VerifiedFixture.TemperatureId);
        var samples = pda.GetSamplesBetween(session.StartTime, end);

        Assert.Equal(100, samples.SampleCount);
        Assert.Equal(VerifiedFixture.Temperature(99), samples.Data[samples.SampleCount - 1], precision: 6); // 29.9
    }

    [Fact]
    public void ReadPressure_IsConstant()
    {
        using var client = LoadSession();
        var session = client.Session;

        using var pda = session.CreateParameterDataAccess(VerifiedFixture.PressureId);
        var samples = pda.GetSamplesBetween(session.StartTime, session.EndTime);

        Assert.Equal(VerifiedFixture.PressureSampleCount, samples.SampleCount);
        for (var i = 0; i < samples.SampleCount; i++)
        {
            Assert.Equal(VerifiedFixture.PressureConstant, samples.Data[i], precision: 6);
        }
    }

    [Fact]
    public void MultiRate_TemperatureHasTwiceAsManySamplesAsSpeed()
    {
        using var client = LoadSession();
        var session = client.Session;

        using var tempPda = session.CreateParameterDataAccess(VerifiedFixture.TemperatureId);
        using var speedPda = session.CreateParameterDataAccess(VerifiedFixture.SpeedId);

        var temp = tempPda.GetSamplesBetween(session.StartTime, session.EndTime);
        var speed = speedPda.GetSamplesBetween(session.StartTime, session.EndTime);

        Assert.Equal(VerifiedFixture.TemperatureSampleCount, temp.SampleCount); // 1000 @ 100 Hz
        Assert.Equal(VerifiedFixture.SpeedSampleCount, speed.SampleCount);       // 500  @ 50 Hz
        Assert.Equal(2 * speed.SampleCount, temp.SampleCount);
        Assert.Equal(VerifiedFixture.Speed(speed.SampleCount - 1), speed.Data[speed.SampleCount - 1], precision: 6); // 99.8
    }
}
