<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SqlRace.Examples.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MESL.SQLRace.API" Version="$(SqlRaceApiVersion)" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.*" />
  </ItemGroup>

</Project>
