<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MAT.ATLAS.SupportFilesLite" Version="*" />
    <PackageReference Include="MESL.SQLRace.API" Version="2.1.26152.20-dev" />
  </ItemGroup>
  <PropertyGroup>
    <StartupObject>MAT.SQLRace.HelloData.Program</StartupObject>
  </PropertyGroup>
</Project>